### ISSUE TITLE
What's index.html and how does it relate to this

### ISSUE THREAD

**Issue by gsnedders** [w3c/testing-how-to#1]
It's unclear quite why that's the index and the README isn't?

**Comment by plehegar** [comment]
Here is my interpretation:
- index.html is a set of slides that can be used to present tests to groups. It is not intended to contain well crafted and obscure wording since those are slides.
- README.md is the canonical version of testing how-to. It ought to be thorough.

**Comment by gsnedders** [comment]
Can we rename index.html then? presentation.html or something?

**Comment by plehegar** [comment]
Sure. I added a dummy index.html to avoid breaking folks linking to the current set of slides. Feels better?

**Comment by gsnedders** [comment]
Looks good to me!
